apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  # match key-value of deployment / pod labels
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      # container port number i.e. forwarding the requests which were
      # received on port 80 to target port 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8080
